### ISSUE TITLE
Add it as package in Sublime Package Manager

### ISSUE THREAD

**Issue by piqus** [samuelrafo/elementary#2]
I'd love to download it directly via [Sublime Text Package Manger](https://github.com/wbond/package_control_channel), please, could you add it?

Here is link [how to submit package to Sublime Package Control](https://sublime.wbond.net/docs/submitting_a_package).

**Comment by orschiro** [comment]
+1 for this. That would make the installation easier. 

Thanks!

Robert

**Comment by garrya** [comment]
+1 as well. It's a great theme and would definitely help with installation time.

**Comment by cassidyjames** [comment]
+1!

**Comment by piqus** [comment]
@samuelrafo I would like to release this theme (merged with my [fork](https://github.com/piqus/elementary)) under my GitHub account into Package Control into piqus/sublime-elementary#1. Do you have any reservations to it?

**Comment by piqus** [comment]
Today, `Theme - Elementary`  package has been added into Package Control ([piqus/sublime-elementary](https://github.com/piqus/sublime-elementary) repository). As credit I am obliged to mention that I am currently using  @samuelrafo light theme updated to latest ST3. I guess it can be closed by now.

**Comment by orschiro** [comment]
@piqus 

Installed without any issues. Thanks very much!
